ALTER TABLE sprints ALTER COLUMN status DROP DEFAULT;
ALTER TABLE sprints ALTER COLUMN status TYPE VARCHAR(20) USING status::text;
ALTER TABLE sprints ALTER COLUMN status SET DEFAULT 'PLANNING';
DROP TYPE IF EXISTS sprint_status;
