# config-server/src/main/resources/config/planning-service.yml
server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://postgres-planning:5432/planningdb
    username: planninguser
    password: planningpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
